#ifndef BASE_HPP
#define BASE_HPP

#include "../inc/common.hpp"

#include "Entity.hpp"
#include "BasicShape.hpp"
#include "LevelShape.hpp"
#include "BasicUtils.hpp"
#include "MapUtils.hpp"

class Base {
private:
    // Saves the amount of time generated by the timeUtil.
    BasicUtils ut;
    float totalTime;

    MapUtils mu;

    sf::RenderWindow window;
    sf::View view;

    Entity player;
    std::vector<sf::FloatRect> playerBorders;
    sf::Vector2f playerMoveAmount;
    sf::Vector2f playerStartPosition;

    int currentLevel;
    int currentStage;

    bool buildMode;

    std::vector<LevelShape> collides;

    std::vector<LevelShape> objects;

    std::vector<LevelShape> rooms;
    std::vector<LevelShape> roomWalls;
    std::vector<LevelShape> corridors;
    std::vector<LevelShape> corridorWalls;

public:

    // Init class.
    Base();

    // Init functions.
    void createWindow();
    void createPlayer();

    // Main Functions.
    bool gameLoop();
    bool checkControls();

    // Required by checkControls().
    float calculateFrameStep();
    void checkMoves();

    // Required by checkMoves().
    void updatePlayerBorders();
    void fadeForeGround();
    void drawWindow();
};

#endif
